### PR TITLE
Inventory Management System using Python

### PR DESCRIPTION
**Pull request by Prabhath-07**
A simple Inventory Management System with Records and Sales data in json format

### CODE REVIEW

**Comment by VinayakTekade** [comment]
@Prabhath-07  could you please add a `README.md` file for your code? We would like to keep it simple for newcomers.

**Comment by Prabhath-07** [comment]
@VinayakTekade Done 👍

**Comment by VinayakTekade** [comment]
@Prabhath-07 Thanks for your quick response. Nice work with the project.

**Review by VinayakTekade — APPROVED** [review]

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
@Prabhath-07 Your `Python/US_Cars_Analysis.ipynb` isn't a valid file. I can see HTML instead as seen here: https://github.com/DSC-ASEB/Hacktoberfest/blob/13d29e323e4b45ef966922f8f90ad3d88fc02f91/Python/US_Cars_Analysis.ipynb?short_path=705a514

**Comment by aravindvnair99** [comment]
> @Prabhath-07 Your `Python/US_Cars_Analysis.ipynb` isn't a valid file. I can see HTML instead as seen here: https://github.com/DSC-ASEB/Hacktoberfest/blob/13d29e323e4b45ef966922f8f90ad3d88fc02f91/Python/US_Cars_Analysis.ipynb?short_path=705a514

Also, I noticed it's copy-pasted from here: https://github.com/AshishJangra27/Skill-India-AI-ML-Scholarship/blob/main/US%20Cars%20Manifacturing%20Analysis/US_Cars_Analysis.ipynb. Plagiarism isn't allowed.

**Review by aravindvnair99 — APPROVED** [review]

**Pull request merged**
