### PR TITLE
Added a C++ program to implement OOPs for a box

### PR DESCRIPTION
**Pull request by kanishkasrivastava**
## Proposed Changes
Design a class named Box whose dimensions are integers and private to the class. The dimensions are labelled: length l , breadth b, and height h.

### CODE REVIEW

**Review by VinayakTekade — CHANGES_REQUESTED** [review]
Could please edit the PR format? I understand it is urgent for you but please maintain proper formatting and mention how you are contributing to this repository.

**Comment by VinayakTekade** [comment]
Also please remove the changes in the `CONTRIBUTING.md` file since it is not relevant to this repository.

**Review by kanishkasrivastava — COMMENTED** [review]
Made changes to the contributing.md and added solutions to issues and added files to the folders python c++

**Comment by kanishkasrivastava** [comment]
All changes are done sir

**Comment by VinayakTekade** [comment]
I can only see the c++ file. Also, could you update this PR to describe what your code does? See other [PRs ](https://github.com/DSC-ASEB/Hacktoberfest/pulls) here for reference. You could also refer to [Best Pull Request Practices] here.

**Comment by kanishkasrivastava** [comment]
is it okay now?

**Comment by kanishkasrivastava** [comment]
i have created a new pull request with all things correct in my new pull
request please see that also

**Comment by VinayakTekade** [comment]
I have edited it for you. Have a look and make PRs like this from now onwards. Happy Learning!

**Review by VinayakTekade — APPROVED** [review]

**Comment by kanishkasrivastava** [comment]
Oh thanks a lot as I am a first year student.

**Review by aravindvnair99 — CHANGES_REQUESTED** [review]
Hey @kanishkasrivastava! Could you provide some context for the program? I went through your code but didn't understand the purpose of the code. Could you explain the inputs?

Maybe add them as comments to the top of the file so that anyone who runs it can understand what the code is meant to do and also what inputs to provide.

Could you also add some helper text for all `cin` as a user might not know that input is required? Ideally, you should prompt the user - `Enter ....: `

**Comment by aravindvnair99** [comment]
Hey @kanishkasrivastava!

Just a reminder... Today is the last date for Hacktoberfest.

**Comment by kanishkasrivastava** [comment]
Updated.  what taking so long merge it sir i did all the changes

**Comment by aravindvnair99** [comment]
> Updated. what taking so long merge it sir i did all the changes

Hey @kanishkasrivastava! Please take a look at my comment on the GitHub interface than via email. Check this: https://github.com/DSC-ASEB/Hacktoberfest/pull/26#pullrequestreview-793595244

**Review by kanishkasrivastava — COMMENTED** [review]
Review #26 solved

**Review by aravindvnair99 — APPROVED** [review]

**Review by VinayakTekade — APPROVED** [review]

**Pull request merged**
